--Geografie vragen
(400, 'Welke brug in Rotterdam heeft de volgende bijnaam: De zwaan?', 4, 'multiple_choice'),
(401, 'Rotterdam is de hoofdstad van Nederland.', 4, 'multiple_choice'),
(402, 'Rotterdam is de hoofdstad van Zuid-Holland.', 4, 'multiple_choice'),
(403, 'Rotterdam is de grootste stad van Nederland.', 4, 'multiple_choice'),
(404, 'De haven van Rotterdam is de grootste haven van Nederland.', 4, 'multiple_choice'),
(405, 'Wat is het belangrijkste vervoersmiddel in Rotterdam?', 4, 'multiple_choice'),
(406, 'Hoeveel millimeter regen valt er gemiddeld per jaar in Rotterdam?', 4, 'multiple_choice'),
(407, 'Hoeveel woningen zijn er ongeveer in Rotterdam?', 4, 'multiple_choice'),
(408, 'Wat is het oudste gebouw van Rotterdam?', 4, 'multiple_choice'),
(409, 'Hoeveel mensen maken dagelijks gebruik van het openbaar vervoer in Rotterdam?', 4, 'multiple_choice'),
(410, 'Wat is de oudste brug van Rotterdam?', 4, 'multiple_choice'),
(411, 'Rotterdam word ook wel de … genoemd', 4, 'multiple_choice'),
(412, 'In welke provincie ligt Rotterdam?', 4, 'multiple_choice'),
(413, 'Hoe heet de grootste rivier waar Rotterdam aan grenst?', 4, 'multiple_choice'),
(414, 'De afstand tussen Rotterdam is ongeveer?', 4, 'multiple_choice'),
(415, 'Hoe groot is Rotterdam, inclusief wateren? (Schat op 50km2 nauwkeurig.)', 4, 'open'),
(416, 'Hoe hoog is de Euromast? (Schat tot op 5 meter nauwkeurig.)', 4, 'open'),
(417, 'Wat is het hoogste gebouw van Rotterdam?', 4, 'open'),
(418, 'Hoe heten de bekendste huizen van Rotterdam?', 4, 'open'),
(419, 'Hoe heet de berg die in Rotterdam ligt?', 4, 'open'),
(420, 'Hoe heet het monument dat op een kerstboom had moeten lijken?', 4, 'open'),
(421, 'Welke stad is groter dan Rotterdam?', 4, 'open'),
(422, 'Welk klimaat heerst er in Rotterdam?', 4, 'open'),
(423, 'Noem minimaal 3 deelgemeentes uit Rotterdam.', 4, 'open'),
(424, 'Welke snel-of-autowegen liggen er langs of door Rotterdam?', 4, 'open'),
(425, 'Wat is de hoogste brug van Rotterdam?', 4, 'open'),
(426, 'Hoeveel winkels telt Rotterdam? (Schat tot op 500 winkels nauwkeurig)', 4, 'open'),
(427, 'Hoeveel auto’s staan er ongeveer geregistreerd in Rotterdam? (Schat tot op 5000 auto’s nauwkeurig)', 4, 'open'),
(428, 'Wat is de oudste deelgemeente van Rotterdam?', 4, 'open'),
(429, 'Hoeveel mensen wonen er ongeveer in Rotterdam? (Schat tot op 5000 mensen nauwkeurig.)', 4, 'open')

--Geografie antwoorden
('De Willemsbrug', 400, FALSE),
('De Erasmusbrug', 400, TRUE),
('De van Briennenoordbrug', 400, FALSE),
('Waar', 401, FALSE),
('Niet waar', 401, TRUE),
('Waar', 402, FALSE),
('Niet waar', 402, TRUE),
('Waar', 403, TRUE),
('Niet waar', 403, FALSE),
('Waar', 404, TRUE),
('Niet waar', 404, FALSE),
('Metro', 405, TRUE),
('Auto', 405, FALSE),
('Fiets', 405, FALSE),
('760 tot 780mm', 406, FALSE),
('780 tot 800mm', 406, FALSE),
('800 tot 820mm', 406, TRUE),
('150.000', 407, FALSE),
('300.000', 407, TRUE),
('450.000', 407, FALSE),
('Kerktoren hillegondakerk', 408, TRUE),
('St. Laurenskerk.', 408, FALSE),
('Stadhuis van Rotterdam', 408, FALSE),
('800.000', 409, FALSE),
('900.000', 409, FALSE),
('1.000.000', 409, TRUE),
('De Willemsbrug', 410, FALSE),
('De Koninginnebrug', 410, TRUE),
('De van Briennenoordbrug', 410, FALSE),
('Stad der wonderen', 411, FALSE),
('Stad der steden', 411, FALSE),
('Haven stad', 411, TRUE),
('Noord-Holland', 412, FALSE),
('Zuid-Holland', 412, TRUE),
('Noord-Brabant', 412, FALSE),
('De Maas', 413, TRUE),
('De Rijn', 413, FALSE),
('De Waal', 413, FALSE),
('50 tot 60km', 414, FALSE),
('60 tot 70km', 414, FALSE),
('70 tot 80km', 414, TRUE),
('319,4', 415, TRUE),
('185', 416, TRUE),
('De Maastoren', 417, TRUE),
('De kubuswoningen', 418, TRUE),
('Rotterdam heeft geen bergen', 419, TRUE),
('Kabouter buttplug, Santa Claus', 420, TRUE),
('Geen, Rotterdam is de grootste stad van Nederland', 421, TRUE),
('Gematigd zeeklimaat', 422, TRUE),
('Rotterdam Centrum, Charlois, Delfshaven, Feijenoord, Hillegersberg, Schiebroek, Hoek van Holland, Hoogvliet, IJsselmonde, Kralingen-Crooswijk, Noord, Overschie, Pernis, Prins Alexander, Rozenburg', 423, TRUE),
('A13, A15, A16, A20.', 424, TRUE),
('De Erasmusbrug', 425, TRUE),
('9455', 426, TRUE),
('200.000', 427, TRUE),
('Rotterdam-Noord', 428, TRUE),
('610.000', 429, TRUE)